name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t nest-lms-backend .
          docker tag nest-lms-backend foysal0075/nest-lms-backend:nest-lms-backend
          docker push foysal0075/nest-lms-backend:nest-lms-backend
